#!/bin/sh
# Schedules a weekly Superwhisper optimization run (Mondays 9:00) via launchd.
#   Claude Code (default): curl -fsSL <this file's raw URL> | sh
#   Codex:                 curl -fsSL <this file's raw URL> | sh -s -- --codex
#   Remove the schedule:   curl -fsSL <this file's raw URL> | sh -s -- --remove
set -e
LABEL="com.superwhisper.optimize-weekly"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
RUNNER="$HOME/Library/Application Support/Superwhisper/optimize-weekly.sh"
LOG="$HOME/Library/Logs/superwhisper-optimize.log"
PROMPT="Run the superwhisper-optimize skill non-interactively: fresh pass over my latest history, sensible defaults, additive changes only."

if [ "$1" = "--remove" ]; then
  launchctl unload "$PLIST" 2>/dev/null || true
  rm -f "$PLIST" "$RUNNER"
  echo "Removed the weekly optimization schedule."
  exit 0
fi

# Locate the active Superwhisper folder; the agent runs with this as its
# working directory so its sandbox covers the files it needs to change.
PARENT=$(defaults read com.superduper.superwhisper appFolderDirectory 2>/dev/null || true)
if [ -n "$PARENT" ] && [ -d "$PARENT/superwhisper/modes" ]; then
  SW_DIR="$PARENT/superwhisper"
elif [ -d "$HOME/Documents/superwhisper/modes" ]; then
  SW_DIR="$HOME/Documents/superwhisper"
elif [ -d "$HOME/superwhisper/modes" ]; then
  SW_DIR="$HOME/superwhisper"
else
  echo "Could not find your Superwhisper folder (no modes/ directory)." >&2
  echo "Open Settings -> Configuration -> Advanced to see its location." >&2
  exit 1
fi

# POSIX single-quote escaping: wrap in quotes, replace each ' with '\''.
# Keeps folders containing spaces, apostrophes, or & working.
shquote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

QDIR=$(shquote "$SW_DIR")
QLOG=$(shquote "$LOG")
QPROMPT=$(shquote "$PROMPT")

# The command lives in its own shell script, never inside the plist, so no
# shell metacharacter can corrupt the XML.
mkdir -p "$(dirname "$RUNNER")" "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"
if [ "$1" = "--codex" ]; then
  RUNCMD="codex exec -C $QDIR -s workspace-write --skip-git-repo-check $QPROMPT"
else
  RUNCMD="cd $QDIR && claude -p $QPROMPT --allowedTools 'Skill,Bash,Read,Write,Edit'"
fi

cat > "$RUNNER" <<RUNNER_EOF
#!/bin/zsh -l
# Generated by the Superwhisper optimize scheduler. Safe to delete.
$RUNCMD >> $QLOG 2>&1
RUNNER_EOF
chmod +x "$RUNNER"

# Build the plist with plutil so every value is escaped properly.
rm -f "$PLIST"
plutil -create xml1 "$PLIST"
plutil -insert Label -string "$LABEL" "$PLIST"
plutil -insert ProgramArguments -array "$PLIST"
plutil -insert ProgramArguments -string "/bin/zsh" -append "$PLIST"
plutil -insert ProgramArguments -string "$RUNNER" -append "$PLIST"
plutil -insert StartCalendarInterval -dictionary "$PLIST"
plutil -insert StartCalendarInterval.Weekday -integer 1 "$PLIST"
plutil -insert StartCalendarInterval.Hour -integer 9 "$PLIST"
plutil -insert StartCalendarInterval.Minute -integer 0 "$PLIST"
plutil -lint "$PLIST" >/dev/null

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "Scheduled weekly optimization (Mondays 9:00)."
echo "Superwhisper folder: $SW_DIR"
echo "Log: $LOG"
echo "Remove later with: sh schedule.sh --remove"
